remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
# Software Effort Estimation Course
title: "Software Effort Estimation Course"
description: "PC2544 - Technical Training for Software Development Teams"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation structure
header_pages:
  - index.md
  - exercises/index.md
  - references/index.md
  - tools/index.md

# Course information
course:
  code: "PC2544"
  title: "Software Effort Estimation"
  duration: "1 day (9am - 5pm)"
  provider: "SBL-Khas 10001577082"

# GitHub repository
repository: "dvwl/software-effort-estimation-course"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - demos/
  skin: auto
title: Software Effort Estimation Course (PC2544)
description: Hands-on exercises and materials for the Software Effort Estimation course by DreamCatcher Consulting Sdn Bhd - Learn techniques for accurate project estimation in software development.
author: Ts. Daniel Vong
github_username: dvwl

# Just the Docs specific settings
search_enabled: true
heading_anchors: true
nav_sort: case_insensitive
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme
color_scheme: light

# Footer content
footer_content: "Copyright &copy; 2025 Daniel Vong. Distributed by an <a href=\"https://github.com/dvwl/software-effort-estimation-course/tree/main/LICENSE\">MIT license.</a>"

# Navigation structure
nav_external_links:
  - title: Course Info
    url: https://www.dreamcatcher.asia/training/2544
